version: "3.9"
services:
  flask:
    build: .
    ports:
      - "8000:8000"
  postgres:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: bePG2jqRxmRZiz
    ports:
      - "5432:5432"
