version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/home/app/web
    depends_on:
      - postgres
  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=bePG2jqRxmRZiz
  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@liamg.com
      - PGADMIN_DEFAULT_PASSWORD=supersecret
    depends_on:
      - postgres
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./purejsfrontend:/home/app/web/purejsfrontend
      - ./frontend:/home/app/web/frontend
    ports:
      - 80:80
    depends_on:
      - web
      - pgadmin4
